name = "smarttd-push"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
NTFY_TOPIC = "smarttd-monitor"
VAPID_PUBLIC_KEY = "TU_CLAVE_PUBLICA_BASE64"
VAPID_SUBJECT = "mailto:tu-email@dominio.com"

[[kv_namespaces]]
binding = "SUBS"
id = "ID_QUE_TE_DEVOLVIO_WRANGLER"
